### ISSUE TITLE
Ability to open server feature logs 

### ISSUE THREAD

**Issue by ItaySar** [microsoft/EventLogExpert#144]
For example, being able to open a Directory services log and seeing the description for the events.
Currently I can open such logs but the description is empty.

**Comment by bill-long** [comment]
There seems to be a bug with the way we resolve events from the Microsoft-Windows-ActiveDirectory_DomainService provider specifically. Other providers that log to that log, such as NTDS ISAM, appear to work.

Investigating.

**Comment by bill-long** [comment]
This is fixed in the release that will be up later today:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/bd0a561b-de27-497d-b1b7-2bdf8f2fd632)

Note that if you created event databases that you are using to resolve these events, those databases will need to be updated with the latest EventDbTool. You may need to close EventLogExpert, and manually clear out the %localappdata%\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases in order to replace the old provider databases with new ones.

**Comment by ItaySar** [comment]
Thanks, this now works as expected
