### ISSUE TITLE
When disabling a filter - it doesn't stay on the same date/time event Log - jumps back to top of log

### ISSUE THREAD

**Issue by jdickson289** [microsoft/EventLogExpert#229]
Downloaded latest version  23.7.7.1304
When disabling a filter, if you are in the middle of the event log -jumps back to top of event log.

I would like to see it stay at the same part of the event log when toggling filters and not jump back to top when filtering. 
Causes user to have to scroll/move back down into the log. 
Thanks.

**Comment by jschick04** [comment]
Waiting on a fix in .NET before we can resolve this one...see the other issue files #198

**Comment by bill-long** [comment]
This is related to #198. Blazor's Virtualize has no way to control the scroll position, and it looks like https://github.com/dotnet/aspnetcore/issues/26943 got moved to the backlog _again_ 3 weeks ago. So dotnet team isn't going to fix it anytime soon.

We are going to have to write our own Virtualize in order to fix this.
