### ISSUE TITLE
Several events show empty description, but data is there in the XML

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#231]
I see this for an AAD operational event, but I saw similar for a Group Policy event:
![image](https://github.com/microsoft/EventLogExpert/assets/41573578/ba0b6ea0-83de-4d2a-8c7f-6a4d1d561547)

in built-in viewer this is:
Log Name:      Microsoft-Windows-AAD/Operational
Source:        Microsoft-Windows-AAD
Date:          18.08.2023 10:44:38
Event ID:      1241
Task Category: AadCloudAPPlugin Operation
Level:         Information
Keywords:      Operational
User:          SYSTEM
Computer:      DUB-CZC74970ZD.TourismIreland.local
Description:
On-prem tgt error: On-prem configuration is missing
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-AAD" Guid="{4de9bc9c-b27a-43c9-8994-0915f1a5e24f}" />
    <EventID>1241</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000010</Keywords>
    <TimeCreated SystemTime="2023-08-18T08:44:38.7290903Z" />
    <EventRecordID>396058</EventRecordID>
    <Correlation />
    <Execution ProcessID="896" ThreadID="20664" />
    <Channel>Microsoft-Windows-AAD/Operational</Channel>
    <Computer>DUB-CZC74970ZD.TourismIreland.local</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="value">On-prem configuration is missing</Data>
  </EventData>
</Event>

It would help if you could populate the description on such an event.

**Comment by bill-long** [comment]
@HerbertMauerer Do you have an event log you can share which contains this event? None of my labs have it.

**Comment by bill-long** [comment]
It looks like we're trying to resolve the event from the older Windows databases first. I'm trying to figure out why, because we have some code that is supposed to make sure we check the Windows 2022 database first. In the meantime, you can work around this by disabling all Windows databases except the Windows 2022 database:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/57496089-3a70-4b80-a3a7-c25e6aea03f8)

As long as it can only use the Windows 2022 database, it correctly resolves the description.

**Comment by bill-long** [comment]
This is fixed in the prerelease that just went live.
