### ISSUE TITLE
Extremely high memory usage when opening large event log files.

### ISSUE THREAD

**Issue by takondo** [microsoft/EventLogExpert#371]
When I opened a 2GB event log file (with 3,574,620 events), it took a few minutes to open and the memory usage kept going up. By the time it finished opening the file, it was 20GB of RAM. 20GB for a 2GB file seems a bit excessive.

![image](https://github.com/user-attachments/assets/906f14fc-12a6-4bb3-9c78-1d97256d6779)

**Comment by jschick04** [comment]
This is because the XML and description string data takes up a large amount of space.

We could make the description and XML more dynamic to save on memory, but this would add a significant amount of time to loading and filtering.

Currently I am trying to decide on a few options to help with this. One would be to have a tool that can split the event log files into smaller chunks and the other option would be to have a toggle for XML data. Basically, if you don't plan on filtering on XML data then that can be turned off to save about 1/3 of the memory.

**Comment by jschick04** [comment]
For comparisons sake, how much memory does this log use if you open it in the Event Viewer mmc?

**Comment by jschick04** [comment]
Would also recommend getting on the preview build as we have made a few optimizations that should hopefully reduce that memory usage.

**Comment by takondo** [comment]
This was actually on the latest prerelease (ver 24.7.18.1054). 

I understand there's no good solution here. I think both options will help - personally I would say splitting the log files since you're probably going to want to filter events to find the one you want when the file is so big.
