### ISSUE TITLE
Multiple filters are always using "AND" operator, too inflexible

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#87]
This is not working well for a number of reasons.
EvPro used implicit OR in each category, e.g. source, category, Event ID included and excluded.

Either do this or allow to specify the logic operator and support bracketing. I'm aware this adds a lot of work in the UI.

**Comment by chcart** [comment]
I believe the subfilter contrains it to the same category though.  What if you want Event ID X or description Y?

**Comment by jschick04** [comment]
Initially it did but I switched it to be constrained for type safety when we switched to dynamic values. I do plan on revisiting this once I do the dynamic inputs #64 and will more than likely open it up to work with multiple categories but each main filter will probably still be "AND" between filters.

**Comment by bill-long** [comment]
#117 allows you to type in a text filter:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/63978e0d-f431-4fe4-a9d9-7a31a6d423fa)

You can see a sample filter in the placeholder. This will be used as a Where clause against the DisplayEventModel objects:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/597133c1-3bfd-4db4-a569-927e806e1b93)

So, you can filter against any property on DisplayEventModel. Note that Xml.Contains() will be slower on large logs since the Xml has to be generated:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/a4fbae59-b202-4dd5-a804-aa2e4e6c0553)

This feature is in the release that just went up. Enhancing the standard filtering UI is still on the agenda for later. You can also use them together.
