### ISSUE TITLE
Ability to resolve replacement strings, I think most prominently seen in security events

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#92]
I find these in security events 4624:
Logon Information:
	Logon Type:		5
	Restricted Admin Mode:	-
	Virtual Account:		%%1843
	Elevated Token:		%%1842

Impersonation Level:		%%1833

I'm not even sure there is a decent way to resolve these from saved events.

I can't open the live security eventlog to check whether this works there.

**Comment by bill-long** [comment]
Turns out these strings are stored in the ParametersFilePath:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/e721f798-5d96-4c90-8133-c27b82b55717)

This will require a change to the way we resolve from local providers and a database schema change to support resolving these from databases.

**Comment by bill-long** [comment]
I have this working, but there's one wrinkle - you _have_ to use databases. We cannot resolve these using the local providers:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/29b9d320-1d1d-4be3-ae1e-522bd20df113)

There seems to be something that prevents EventLogExpert from reading the resources out of the dll. I'm guessing it has something to do with how we restrict modern apps access to the system, because it works fine when we read the resources from a unit test or from EventDbTool.

So, we can make a database that has these strings in it, and EventLogExpert can resolve from that. But it can't resolve them without the database.
